services:
  ruby26:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      args:
        RUBY_VERSION: 2.6

  ruby27:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      args:
        RUBY_VERSION: 2.7

  ruby30:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      args:
        RUBY_VERSION: 3.0

  ruby32:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      args:
        RUBY_VERSION: 3.2

  ruby33:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      args:
        RUBY_VERSION: 3.3