name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
test:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3' ]
      bundler: [ '1.17.3', '2.3.26', '2.4.22', '2.4.22', '2.4.22', '2.4.22' ]
  name: Ruby ${{ matrix.ruby }} with Bundler ${{ matrix.bundler }}
  steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake test
